修复：无法更新贴吧列表
MoeNetwork/Tieba-Cloud-Sign pull request #187
Opened 2022-09-01 02:29 UTC by BANKA2017

近期贴吧在tc使用的接口移除了 `uid` 值，因此tc无法取得用户 `uid`，进而无法通过使用函数 `scanTiebaByPid()` 刷新用户的贴吧列表。此更新恢复使用 `getTieba2()` 取得用户的贴吧列表

2022-09-01 15:33 UTC, BANKA2017 commented
修复 php8.1 环境下 `/templates/admin-cron.php` 中对 `null` 进行 `str_replace` 处理

2022-09-04 02:26 UTC, n0099 requested changes

2022-09-04 02:26 UTC, n0099 commented on lib/class.misc.php
> +		}
```suggestion
        while (true){
            //if (empty($bid)) break;
            $rc = self::getTieba2($bduss, $stoken, $pn);//fetch forum list //default 200 per page
            $rc = json_decode($rc,true);
            if(!$rc) {break;}
            $ngf = isset($rc["data"]["like_forum"]["list"]) ? $rc["data"]["like_forum"]["list"] : [];
            foreach ($ngf as $v){
                if ($tb['c'] + $a >= $o && !empty($o) && !$isvip) break;
                $vn  = addslashes(htmlspecialchars($v['forum_name']));
                $ist = $m->once_fetch_array("SELECT COUNT(id) AS `c` FROM `".DB_NAME."`.`".DB_PREFIX.$table."` WHERE `pid` = {$pid} AND `tieba` = '{$vn}';");
                if ($ist['c'] == 0){
                    $a ++;
                    $m->query("INSERT INTO `".DB_NAME."`.`".DB_PREFIX.$table."` (`pid`,`fid`, `uid`, `tieba`) VALUES ({$pid},'{$v['forum_id']}', {$uid}, '{$vn}');");
                }
            }
            $pn++;
            if ($pn > $rc["data"]["like_forum"]["page"]["total_page"]) {
                break;
            }
        }
```

2022-09-05 03:02 UTC, n0099 approved these changes

2022-09-05 03:02 UTC, merged

2022-09-05 03:54 UTC, n0099 commented
https://github.com/MoeNetwork/Tieba-Cloud-Sign/discussions/186#discussioncomment-3523594
https://github.com/MoeNetwork/Tieba-Cloud-Sign/discussions/191#discussioncomment-3550074