添加2个插件到主线
MoeNetwork/Tieba-Cloud-Sign pull request #219
Opened 2022-10-25 08:26 UTC by Weltolk

[https://github.com/Weltolk/weltolk_sign_qq](https://github.com/Weltolk/weltolk_sign_qq) :

每日用户签到结果qq推送,目前支持go-cqhttp的正向WebSocket和HTTP API,基于D丶L和quericy的版本重写

[https://github.com/Weltolk/weltolk_backup_qq](https://github.com/Weltolk/weltolk_backup_qq) :

每日数据库备份qq推送，目前支持go-cqhttp的正向WebSocket和HTTP API，基于D丶L的版本重写

2023-01-31 17:00 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/weltolk_sign_qq.php
> +    </td>
```suggestion
    </td>
</tr>
```

后面的 `</tr>` 应该放这里

2023-01-31 17:00 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/weltolk_sign_qq.php
> +</tr>
```suggestion

```

这里的 `</tr>` 是多出来的，应该放到前面

2023-02-24 09:36 UTC, BANKA2017 requested changes
使用后发现的小bug，改好了应该就可以合并

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_backup_qq/weltolk_backup_qq_setting.php
> +$page = $_GET['page'];
```suggestion
$page = isset($_GET['page']) ? $_GET['page'] : '';
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_backup_qq/weltolk_backup_qq_websocket.php
> +        if ($uriData['port']) {
```suggestion
        if (isset($uriData['port']) && $uriData['port']) {
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_backup_qq/weltolk_backup_qq_websocket.php
> +        if ($uriData['fragment']) {
```suggestion
        $this->path = (isset($uriData['path']) && $uriData['path']) ? $uriData['path'] : '/';
        if (isset($uriData['query']) && $uriData['query']) {
            $this->path .= '?' . $uriData['query'];
        }
        if (isset($uriData['fragment']) && $uriData['fragment']) {
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/weltolk_sign_qq_show.php
> +$page = $_GET['page'];
```suggestion
$page = isset($_GET['page']) ? $_GET['page'] : '';
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/weltolk_sign_qq_show.php
> +                    . '签到失败' . '\n'
```suggestion
                    . '签到失败' . "\n"
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/cron_weltolk_sign_qq.php
> +                            . '\n\n';
```suggestion
                            . $status_str . "\n"
                            . $style_prefix . ' 详细信息: ' . $msg
                            . "\n\n";
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/websocketclass.php
> +        if ($uriData['port']) {
```suggestion
        if (isset($uriData['port']) && $uriData['port']) {
```

2023-02-24 09:36 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/websocketclass.php
> +        if ($uriData['fragment']) {
```suggestion
        $this->path = (isset($uriData['path']) && $uriData['path']) ? $uriData['path'] : '/';
        if (isset($uriData['query']) && $uriData['query']) {
            $this->path .= '?' . $uriData['query'];
        }
        if (isset($uriData['fragment']) && $uriData['fragment']) {
```

2023-02-24 10:13 UTC, n0099 commented on plugins/weltolk_backup_qq/weltolk_backup_qq_setting.php
> +$page = $_GET['page'];
```suggestion
$page = $_GET['page'] ?? '';
```
https://stackoverflow.com/questions/3210935/whats-the-difference-between-isset-and-array-key-exists

2023-02-24 10:14 UTC, n0099 commented on plugins/weltolk_backup_qq/weltolk_backup_qq_websocket.php
> +        if ($uriData['port']) {
```suggestion
        if (is_numeric($uriData['port'] ?? 默认值)) {
```

2023-02-24 10:15 UTC, n0099 commented on plugins/weltolk_backup_qq/weltolk_backup_qq_websocket.php
> +        if ($uriData['fragment']) {
```suggestion
        $this->path = $uriData['path'] ?? '/';
        $this->path .= '?' . $uriData['query'] ?? '';
        if (array_key_exists('fragment', $uriData)) {
```

2023-02-24 10:16 UTC, n0099 commented on plugins/weltolk_sign_qq/weltolk_sign_qq_show.php
> +$page = $_GET['page'];
```suggestion
$page = $_GET['page'] ?? '';
```

2023-02-24 10:16 UTC, n0099 commented on plugins/weltolk_sign_qq/websocketclass.php
> +        if ($uriData['port']) {
```suggestion
        if ($uriData['port'] ?? 默认值) {
```

2023-02-24 10:17 UTC, n0099 commented on plugins/weltolk_sign_qq/websocketclass.php
> +        if ($uriData['fragment']) {
```suggestion
        $this->path = ($uriData['path'] ?? '/') . '?' . ($uriData['query'] ?? '');
        if (array_key_exists('fragment', $uriData)) {
```

2023-02-24 21:55 UTC, n0099 commented
> 对于php我也不知道哪个更好一些

https://stackoverflow.com/questions/3210935/whats-the-difference-between-isset-and-array-key-exists

2023-02-25 03:04 UTC, BANKA2017 commented
>哪个更好一些

`isset(aa) ? aa : bb` 和 `aa ?? bb` 都是可以用的，只是 `??` 语法糖需要的 PHP 版本是 `7.0+`

至于 `isset` 跟 `array_key_exists` 的区别就看上面n0099发的吧，虽然在本pr的特定环境下用这两个函数都是可以的

2023-02-25 03:14 UTC, n0099 commented
https://stitcher.io/blog/php-8-nullsafe-operator

2023-02-25 03:28 UTC, BANKA2017 commented on plugins/weltolk_sign_qq/websocketclass.php
> +        if ($uriData['port'] ?? 默认值) {
此处的 `默认值` 指的是放个默认的端口上去 （1 ~ 65535），比如 cq-http 用的默认端口

2023-02-25 03:37 UTC, BANKA2017 commented
我还有一个疑问是关于开源协议的问题，已知 go-cqhttp 的协议是 AGPL3.0，本项目的协议是GPLv3，这些插件用到了 go-cqhttp 的私有 API（发送群文件/获取群文件列表），比如

https://github.com/Weltolk/Tieba-Cloud-Sign/blob/bf20acb9511574901ed694dc9fd9f344848f2d98/plugins/weltolk_backup_qq/weltolk_backup_qq_cron.php#L110-L129

这样合并有无影响 @n0099

2023-02-25 03:43 UTC, n0099 commented
https://opensource.stackexchange.com/questions/8432/is-gpl-linking-to-agpl-possible
> 这在 GPLv3 的第 13 节（以及相应的 AGPLv3 的第 13 节）中明确处理，它阐明了 GPLv3 和 AGPLv3 许可代码在组合时的交互：
> > 13. 使用 GNU Affero 通用公共许可证。
> > 尽管本许可证有任何其他规定，您有权将任何涵盖的作品与根据 GNU Affero 通用公共许可证第 3 版许可的作品链接或组合成一个单一的组合作品，并传达由此产生的作品。本许可证的条款将继续适用于涵盖作品的部分，但 GNU Affero 通用公共许可证第 13 节关于通过网络进行交互的特殊要求将同样适用于组合。

2023-02-25 04:29 UTC, n0099 commented
因为有些人（我不说是谁，切勿对号入座）还在死守十年前的php56
然而[`array_key_exists()`](https://www.php.net/manual/en/function.array-key-exists.php)是php4时代就有了的

![image](https://user-images.githubusercontent.com/13030387/221338128-3c763973-9da7-460b-913b-7b41403c42ae.png)
另外commit msg里您可以写`Co-authored-by: username <email>`
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

2023-02-25 04:34 UTC, BANKA2017 commented
>鉴于本项目中(主程序和其他插件)并未有使用过??语法糖和array_key_exists()函数

本pr提交的是插件，只要在相关字段说清楚最低php版本即可，并不强制要求兼容到5.x

2023-02-25 04:45 UTC, n0099 commented
> > > 鉴于本项目中(主程序和其他插件)并未有使用过??语法糖和array_key_exists()函数
> > 
> > 
> > 本pr提交的是插件，只要在相关字段说清楚最低php版本即可，并不强制要求兼容到5.x
> 
> 明白, 个人认为本pr提交的插件和主程序的代码保持统一比较好

建议先跟[PSR-12](https://www.php-fig.org/psr/psr-12/)统一：https://github.com/MoeNetwork/Tieba-Cloud-Sign/pull/180

2023-02-25 07:03 UTC, n0099 commented
您直接在repo根目录下run的？导致把其他插件也改了
您[cherry-pick](https://git-scm.com/docs/git-cherry-pick) commit ffdbc1e5613980c887778b54409d08d707105522 出单独的branch发pr吧

2023-02-25 07:11 UTC, n0099 commented
在`Tieba-Cloud-Sign`repo根目录下run
```bash
phpcbf --standard=PSR12 plugins/weltolk_backup_qq
phpcbf --standard=PSR12 plugins/weltolk_sign_qq
```

2023-02-25 08:05 UTC, n0099 approved these changes

2023-02-25 08:14 UTC, BANKA2017 approved these changes

2023-02-25 08:46 UTC, merged