使用`PHP_CodeSniffer`使所有文件 PSR-12 化
MoeNetwork/Tieba-Cloud-Sign pull request #231
Opened 2023-02-25 09:00 UTC by n0099

https://github.com/MoeNetwork/Tieba-Cloud-Sign/pull/180
https://github.com/MoeNetwork/Tieba-Cloud-Sign/pull/219#issuecomment-1445000293

2023-02-25 11:36 UTC, BANKA2017 requested changes

2023-02-25 11:39 UTC, n0099 commented on plugins/ver4_style/css/test.css
> +.ath-android .ath-action-icon { width : 1.4em; height : 1.4em; background-image : url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAANlBMVEVmZmb//9mZmZmZmZmZmZmZmZmZmZmZmZmZmZm
建议重温 #180

2023-02-25 11:41 UTC, n0099 commented on plugins/wmzz_anno/wmzz_anno_setting.php
> +                           } ?> >footer</option>
建议pattern match

2023-02-25 11:56 UTC, n0099 commented on plugins/ver4_style/css/test.css
> +.ath-android .ath-action-icon { width : 1.4em; height : 1.4em; background-image : url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAANlBMVEVmZmb//9mZmZmZmZmZmZmZmZmZmZmZmZmZmZm
https://github.com/squizlabs/PHP_CodeSniffer/issues 里没人报告过这种问题，建议去提issue

2023-02-26 06:01 UTC, BANKA2017 commented on plugins/wmzz_anno/wmzz_anno_setting.php
> +                           } ?> >footer</option>
我记得 `match()` 是只输出一个结果的吧，难道写到函数上去套？大可不必？

2023-02-26 06:09 UTC, BANKA2017 commented on plugins/wmzz_anno/wmzz_anno_setting.php
> +                           } ?> >footer</option>
```suggestion
    <?php 
      $options = ["index_1", "index_2", "index_3", "navi_7", "navi_8", "navi_9", "navi_9", "login_page_1",    "login_page_2", "login_page_3", "reg_page_1", "reg_page_2", "reg_page_3", "header", "footer"];
      foreach($options as $option) {
        echo '<option value="' . in_array($option, $doa) ? 'selected' : '' . '">' . $option . '</option>';
      }
    ?>
```

或者全部塞一块？

2023-02-26 06:57 UTC, n0099 commented on plugins/wmzz_anno/wmzz_anno_setting.php
> +                           } ?> >footer</option>
经典打表法

2023-02-26 07:35 UTC, BANKA2017 approved these changes

2023-02-26 07:38 UTC, BANKA2017 commented on plugins/ver4_style/css/test.css
> +.ath-android .ath-action-icon { width : 1.4em; height : 1.4em; background-image : url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAANlBMVEVmZmb//9mZmZmZmZmZmZmZmZmZmZmZmZmZmZm
>建议重温 https://github.com/MoeNetwork/Tieba-Cloud-Sign/pull/180

那边没多少base64内容吧，我review一般都会对所有更改看一遍的，问题应该不大

2023-02-26 07:53 UTC, n0099 commented on plugins/ver4_style/css/test.css
> +.ath-android .ath-action-icon { width : 1.4em; height : 1.4em; background-image : url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAANlBMVEVmZmb//9mZmZmZmZmZmZmZmZmZmZmZmZmZmZm
> 我review一般都会对所有更改看一遍的

建议立即加入 @CFPAOrg

2023-02-26 07:55 UTC, merged