添加MySQL SSL连接的支持
MoeNetwork/Tieba-Cloud-Sign pull request #273
Opened 2024-12-16 09:48 UTC by boris1993

2024-12-16 10:28 UTC, BANKA2017 commented on lib/class.mysqli.php
> +            $mysqli->ssl_set(null, null, "/etc/ssl/certs/ca-certificates.crt", "/etc/ssl/certs", null);
我对 MySQL SSL 连接不太了解，请问这里直接硬编码没问题吗，MySQL 的证书都会存在这个目录吗

2024-12-16 13:23 UTC, boris1993 commented on lib/class.mysqli.php
> +            $mysqli->ssl_set(null, null, "/etc/ssl/certs/ca-certificates.crt", "/etc/ssl/certs", null);
这个我得再确认下

2024-12-17 05:17 UTC, kenvix requested changes
虽然大多数系统的CA证书都在 `/etc/ssl/certs/ca-certificates.crt`，但存在以下两个典型例外：

- Windows 使用Certificate Stores，没有文件形式的CA路径
- OpenWRT可能只存在 `/etc/ssl/certs` 但不存在 `/etc/ssl/certs/ca-certificates.crt`

2024-12-17 14:36 UTC, boris1993 commented
在Alpine Docker镜像中测试发现，在连接的时候设定`MYSQLI_CLIENT_SSL`这个flag就可以通过SSL连接，并且不需要手动指定CA证书位置。
我接下来用Windows环境再测测。

2024-12-17 18:43 UTC, BANKA2017 commented
> 设定 `MYSQLI_CLIENT_SSL` 这个 `flag` 就可以通过SSL连接

这个操作在当前环境下是合理的，TiDB Cloud 提供的实际上是 Let's Encrypt [自签名版本的根证书 ISRG Root X1](https://letsencrypt.org/certs/isrgrootx1.pem) （可以在[这里](https://letsencrypt.org/certificates/)找到），这玩意兼容性[非常好](https://letsencrypt.org/zh-cn/docs/certificate-compatibility/)，大多数系统的证书库都有收录，所以可以直接添加。

如果用户使用自签名的证书用于数据库连接（真的有人会这么干吗），可能就需要自行将证书导入到系统

2024-12-17 18:47 UTC, BANKA2017 approved these changes
如果测试没有问题，那么**应该**是没有问题了

2024-12-18 01:12 UTC, boris1993 commented
> > 设定 `MYSQLI_CLIENT_SSL` 这个 `flag` 就可以通过SSL连接
> 
> 这个操作在当前环境下是合理的，TiDB Cloud 提供的实际上是 Let's Encrypt [自签名版本的根证书 ISRG Root X1](https://letsencrypt.org/certs/isrgrootx1.pem) （可以在[这里](https://letsencrypt.org/certificates/)找到），这玩意兼容性[非常好](https://letsencrypt.org/zh-cn/docs/certificate-compatibility/)，大多数系统的证书库都有收录，所以可以直接添加。
> 
> 如果用户使用自签名的证书或者没被系统的证书库收录的证书用于数据库连接（真的有人会这么干吗），可能就需要自行将证书导入到系统

如果用的自签名证书或者证书没被收录，那确实用户就得自己解决环境问题了。但我也觉得这应该是非常小众的情况。

2024-12-18 03:27 UTC, kenvix commented on lib/class.mysqli.php
> +                $connected = $mysqli->real_connect('p:' . substr($host, 0, $coninfo), $user, $pw, $name, substr($host, $coninfo + 1), flags: $flags);
注意到使用了命名参数 `flags:` ，我们当前的最低PHP版本要求与这个兼容吗？
@BANKA2017

2024-12-18 04:16 UTC, BANKA2017 commented on setup/install.php
> +                define('DB_SSL', $dbSsl == "1" ? true : false);
```suggestion
                define('DB_SSL', $dbSsl == "1" ? 1 : 0);
```

常量的值需要前后一致，要不统一为 true/false，要不就 1/0

2024-12-18 04:47 UTC, BANKA2017 commented on setup/install.php
> +//MySQL 启用SSL连接，如需启用请将值改为true
```suggestion
//MySQL 启用SSL连接，如需启用请将值改为 1
```

常量的值需要前后一致

2024-12-18 13:02 UTC, boris1993 commented on setup/install.php
> +                define('DB_SSL', $dbSsl == "1" ? true : false);
已更正为统一用1/0

2024-12-18 13:02 UTC, boris1993 commented on setup/install.php
> +//MySQL 启用SSL连接，如需启用请将值改为true
内容已更正

2024-12-20 08:32 UTC, kenvix approved these changes

2024-12-20 17:08 UTC, n0099 requested changes

2024-12-20 17:08 UTC, n0099 commented on config.php
> +define('DB_SSL',0);
```suggestion
define('DB_SSL', 0);
```

2024-12-20 17:08 UTC, n0099 commented on lib/class.S.php
> +    public function __construct($host, $user, $pw, $name, $long = false, $useSsl = false)
```suggestion
    public function __construct($host, $user, $pw, $name, $long = false, $useSSL = false)
```

2024-12-20 17:08 UTC, n0099 commented on lib/class.S.php
> +            parent::__construct($host, $user, $pw, $name, $long, $useSsl);
```suggestion
            parent::__construct($host, $user, $pw, $name, $long, $useSSL);
```

2024-12-20 17:08 UTC, n0099 commented on lib/class.mysql.php
> +    public function __construct($host, $user, $pw, $name, $long = false, $useSsl = false)
```suggestion
    public function __construct($host, $user, $pw, $name, $long = false, $useSSL = false)
```

2024-12-20 17:08 UTC, n0099 commented on lib/class.mysqli.php
> +    public function __construct($host, $user, $pw, $name, $long = false, $useSsl = false)
```suggestion
    public function __construct($host, $user, $pw, $name, $long = false, $useSSL = false)
```

2024-12-20 17:08 UTC, n0099 commented on setup/install.php
> +                echo '<div class="input-group"><span class="input-group-addon">数据库开启SSL</span><select name="dbSsl" class="form-control" required="true"><option value="0">否</option><option value="1">是
```suggestion
                echo '<div class="input-group"><span class="input-group-addon">数据库开启SSL</span><select name="dbssl" class="form-control" required="true"><option value="0">否</option><option value="1">是</option></select></div><br/>';
```

2024-12-20 17:08 UTC, n0099 commented on setup/install.php
> +                echo '<input type="hidden" name="dbSsl" value="0">';
```suggestion
                echo '<input type="hidden" name="dbssl" value="0">';
```

2024-12-20 17:08 UTC, n0099 commented on setup/install.php
> +                echo '<div class="input-group"><span class="input-group-addon">数据库开启SSL</span><select name="dbSsl" class="form-control" required="true"><option value="0">否</option><option value="1">是
```suggestion
                echo '<div class="input-group"><span class="input-group-addon">数据库开启SSL</span><select name="dbssl" class="form-control" required="true"><option value="0">否</option><option value="1">是</option></select></div><br/>';
```

2024-12-20 17:08 UTC, n0099 commented on setup/install.php
> +                define('DB_SSL', $_POST['dbSsl']);
```suggestion
                define('DB_SSL', $_POST['dbssl']);
```

2024-12-20 17:10 UTC, n0099 approved these changes

2024-12-20 17:11 UTC, merged